### ISSUE TITLE
barstyle and horizontal arrow

### ISSUE THREAD

**Issue by Blameur** [EKE00372/EKplates#1]
Hi, i posted in the comments of your addon in wowinterface, my problem is i cant put the red arrow in right side of the barstyle , i love numer style, but i cant handle with the cast bar on icon :/ so can i put the red arrow just in the right of the health bar in bar style? thanks for ur time

**Comment by EKE00372** [comment]
try new version.

**Comment by EKE00372** [comment]
you can use "bar" castbar in number style now.
