### ISSUE TITLE
World Quest "呼喊更多雷霆" issue

### ISSUE THREAD

**Issue by class2u** [EKE00372/EKplates#6]
Thank you for making this great addon. I love it so much. :)

There is a small issue. I got the this error while doing world quest "呼喊更多雷霆". Sorry I don't know the English name of this world quest. It is riding a dragon attack on the 50 people of Stormheim.

Here is the error:

5x EKplates\EKplates-R1.1.lua:872: attempt to call global 'UpdateNamePlateEvents' (a nil value)
EKplates\EKplates-R1.1.lua:872: in function <EKplates\EKplates.lua:866>
EKplates\EKplates-R1.1.lua:913: in function <EKplates\EKplates.lua:912>
EKplates\EKplates-R1.1.lua:1311: in function <EKplates\EKplates.lua:1307>
EKplates\EKplates-R1.1.lua:1365: in function <EKplates\EKplates.lua:1346>
Locals:

**Comment by EKE00372** [comment]
少年，你可以用中文，我的英文差不多是你中午吃太飽打嗝產生的二氧化碳一樣──就他喵的跟平常的二氧化碳沒區別，幹麻強調是中午吃太飽打嗝產生的──不就是個廢字可以說完的嗎！

載具bug，之後修復

**Comment by class2u** [comment]
哈哈，謝謝你! 這個血條插件非常好用!!

**Comment by EKE00372** [comment]
你是不是有開playerplate(玩家個人資源)

**Comment by class2u** [comment]
這個不確定，我有將它開啟過測試功能，然後又關掉，只是不確定解任務的時候是開著還是關的。下次有出現這個世界任務的時候，我再特別注意一下。

另外我有一個關於玩家個人資源條的問題，開另一個 issue 來敘述。感謝~

**Comment by class2u** [comment]
你好!

今天剛好有這個世界任務，再測試了一次，沒有開啟 playerplate，也是一樣會報錯誤。感謝~~

**Comment by EKE00372** [comment]
可是瑞凡
我測試了沒問題啊
你只開ekplates還是有開別的插件？

**Comment by class2u** [comment]
大大安安

我今天又遇到類似的問題，這次特別把插件全部關閉來測試，只開 EKPlate, BugGrabber 和 BugSack。玩家個人資源的設定如下：

C.playerplate = false  --玩家個人資源/player self nameplate
C.classresource_show = false
C.classresource = "player" -- "player", "target"  
C.plateaura = false

這次是在北裂境 龍骨荒野 的新壁爐谷，只要附近有騎在馬上面的敵人，就會持續報錯。馬的血條正常，騎在馬上面的敵人名字顯示未知、血條顯示不出來。麻煩您了~~~

有兩種錯誤訊息：

20x integer overflow attempting to store -1.#IND
[C]: in function `format'
EKplates\EKplates-R1.2.lua:673: in function <EKplates\EKplates.lua:669>
EKplates\EKplates-R1.2.lua:943: in function <EKplates\EKplates.lua:934>

Locals:

另一種是：

14x EKplates\EKplates-R1.2.lua:866: attempt to call global 'UpdateNamePlateEvents' (a nil value)
EKplates\EKplates-R1.2.lua:866: in function <EKplates\EKplates.lua:860>
EKplates\EKplates-R1.2.lua:907: in function <EKplates\EKplates.lua:906>
EKplates\EKplates-R1.2.lua:1312: in function <EKplates\EKplates.lua:1308>
EKplates\EKplates-R1.2.lua:1389: in function <EKplates\EKplates.lua:1370>

Locals:
unitFrame = NamePlate1UnitFrame {
 0 = <userdata>
 iconnumber = 0
 power = <unnamed> {
 }
 r = 0.99999779462814
 g = 0
 icons = <unnamed> {
 }
 unit = "nameplate2"
 castBar = <unnamed> {
 }
 b = 0
 name = <unnamed> {
 }
 redarrow = <unnamed> {
 }
 healthperc = <unnamed> {
 }
 inVehicle = true
 displayedUnit = "nameplatepet2"
 RaidTargetFrame = <unnamed> {
 }
}
prefix = "nameplate"
id = "2"
suffix = ""
(*temporary) = nil
(*temporary) = NamePlate1UnitFrame {
 0 = <userdata>
 iconnumber = 0
 power = <unnamed> {
 }
 r = 0.99999779462814
 g = 0
 icons = <unnamed> {
 }
 unit = "nameplate2"
 castBar = <unnamed> {
 }
 b = 0
 name = <unnamed> {
 }
 redarrow = <unnamed> {
 }
 healthperc = <unnamed> {
 }
 inVehicle = true
 displayedUnit = "nameplatepet2"
 RaidTargetFrame = <unnamed> {
 }
}
(*temporary) = "attempt to call global 'UpdateNamePlateEvents' (a nil value)"

**Comment by EKE00372** [comment]
get it
fix it later
