### ISSUE TITLE
玩家個人資源條與 WeakAuras 相容性 

### ISSUE THREAD

**Issue by class2u** [EKE00372/EKplates#7]
你好!

新版的 WeakAuras 有一個功能是讓建立出來的監控效果對齊到玩家個人資源條，如此一來就可以隨著人物移動，對於使用 ActionCam 功能時特別好用，因為人物不在畫面正中央，會不固定位置。這個功能要開啟遊戲內建的個人資源條才能使用，若沒有開啟，監控效果也不會出現。

使用 EKPlate 時，玩家個人資源條會替換為 EKPlate 的樣式， 這時 WeakAuras 似乎是找不到遊戲內建的個人資源條框架，因此也不會顯示監控效果。

是否有甚麼方法，可以同時使用 EKPlate 和 WeakAuras 對齊個人資源條、隨著人物位置移動的功能? 

我有測試過在 WeakAuras 中將對齊的框架手動指定為 EKNamePlatePowerFrame，監控效果會出現，但不會隨人物位置移動。

不知道是否要指定為其他的 EKPlate 框架名稱，或是可以在 EKPlate 中增加一個選項設定，讓玩家可以選擇要使用 EKPlate 的個人資源條，或是遊戲內建的。或者有其他更好的方法，十分感謝！

WeakAuras 中對齊到個人資源條的設定如下圖：
![wa](https://cloud.githubusercontent.com/assets/420378/23841175/60c2c5d6-07e6-11e7-8738-50ced1435d8b.png)

**Comment by EKE00372** [comment]
怪了
按理可以啊......難不成框體沒命名.....

**Comment by EKE00372** [comment]
NamePlatePlayerResourceFrame
NamePlate1UnitFrame
EKplatesresource

**Comment by EKE00372** [comment]
如果這三個還是不行再把feedback打開
